all: Makefile.rocq
	$(MAKE) -f Makefile.rocq $@

clean: _RocqProject
	# We have to make the coq makefile in case it is missing
	coq_makefile -f $< -o Makefile.rocq
	$(MAKE) -f Makefile.rocq $@
	rm Makefile.rocq Makefile.rocq.conf

Makefile.rocq: _RocqProject
	coq_makefile -f $< -o $@

.DEFAULT:
	$(MAKE) Makefile.rocq
	$(MAKE) -f Makefile.rocq $@

.PHONY: all clean
